[package]
name = "rust-abci"
version = "0.1.0"
authors = ["Adrian Brink <adrian@brink-holdings.com>"]

[dependencies]
futures         = "0.1"
futures-cpupool = "0.1"
grpc            = "0.*"
protobuf        = "1.*"
tls-api         = "0.*"
