[package]
name = "rust-abci"
version = "0.1.0"
authors = ["Adrian Brink <adrian@brink-holdings.com>"]
license = "MIT/Apache-2.0"
description = "An implementation of the ABCI protocol used by Tendermint Core. Allows the building of ABCI apps in Rust."
homepage = "https://tendermint.com/docs/guides/app-development"
repository = "https://github.com/tendermint/rust-abci"
keywords = ["abci", "tendermint", "cosmos", "blockchain", "proof-of-stake"]
categories = ["blockchain", "encoding"]
readme = "README.md"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]

[dependencies]
byteorder       = "1.0"
futures         = "0.1"
futures-cpupool = "0.1"
grpc            = "0.*"
protobuf        = "1.*"
tls-api         = "0.*"
tokio-core      = "0.1.8"
websocket       = "0.20.1"
