[package]
name = "rust-abci"
version = "0.1.0"
authors = ["Adrian Brink <adrian@brink-holdings.com>"]

[dependencies]
byteorder       = "1.0"
futures         = "0.1"
futures-cpupool = "0.1"
grpc            = "0.*"
protobuf        = "1.*"
tls-api         = "0.*"
websocket       = "0.20.1"

[features]
default = []
grpc_support = []
socket_support = []