[package]
name = "abci"
version = "0.3.1"
authors = ["Adrian Brink <adrian@brink-holdings.com>", "Jackson Lewis <st.japa6@gmail.com>", "Dave Bryson"]
license = "MIT/Apache-2.0"
description = "Tendermint ABCI server for Rust"
homepage = "https://tendermint.com/docs/guides/app-development"
repository = "https://github.com/tendermint/rust-tsp"
#documentation = "https://docs.rs/tsp/0.2.3/tsp/"
keywords = ["abci", "tendermint", "blockchain", "rust"]
#categories = ["encoding"]
readme = "README.md"
include = ["src/**/*", "Cargo.toml"]

[dependencies]
bytes = "0.4"
protobuf = "2.0.1"
integer-encoding = "1.0.5"

[build-dependencies]
protoc = "1.4.1"
protobuf-codegen-pure = "2.0.1"
